# Generated by Django 4.2.30 on 2026-04-23 13:30

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('pharmacist', 'Pharmacist'), ('user', 'User')], default='user', max_length=16)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('zip_code', models.CharField(blank=True, default='', max_length=16)),
                ('google_sub', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '_benmore_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.TextField()),
                ('status', models.TextField(default='pending')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_requests',
            },
        ),
        migrations.CreateModel(
            name='DrugShortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.TextField()),
                ('generic_name', models.TextField(blank=True, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='current')),
                ('reason', models.TextField(blank=True, null=True)),
                ('estimated_resolution', models.TextField(blank=True, null=True)),
                ('alternatives', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drug_shortages',
            },
        ),
        migrations.CreateModel(
            name='ModerationKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('category', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'moderation_keywords',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField(default='Philadelphia')),
                ('state', models.TextField(default='PA')),
                ('zip', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('stock_confidence', models.IntegerField(default=0)),
                ('avg_wait_time', models.IntegerField(default=0)),
                ('avg_service_rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_digital', models.IntegerField(default=0)),
                ('website', models.TextField(blank=True, null=True)),
                ('npi_number', models.TextField(blank=True, null=True)),
                ('claimed_by', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(default='active')),
                ('phone_wait_time', models.IntegerField(blank=True, null=True)),
                ('delivery_wait_time', models.IntegerField(blank=True, null=True)),
                ('delivery_rating', models.FloatField(default=0)),
                ('customer_service_hours', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pharmacies',
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='owned_orgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_orgs',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.TextField(blank=True, null=True)),
                ('user_name', models.TextField(blank=True, null=True)),
                ('stock_available', models.IntegerField(default=1)),
                ('wait_time_rating', models.IntegerField(default=3)),
                ('service_rating', models.IntegerField(default=3)),
                ('comment', models.TextField(blank=True, null=True)),
                ('delivery_timeliness', models.IntegerField(blank=True, null=True)),
                ('is_caregiver', models.IntegerField(default=0)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('response_date', models.TextField(blank=True, null=True)),
                ('moderation_status', models.TextField(default='approved')),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('flagged_at', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(blank=True, db_column='pharmacy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='pharmacypulse.pharmacy')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.TextField()),
                ('granted', models.IntegerField(default=0)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_consents',
            },
        ),
        migrations.CreateModel(
            name='SavedComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(db_column='pharmacy_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='pharmacypulse.pharmacy')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_comparisons',
            },
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(blank=True, db_column='org_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_responses', to='pharmacypulse.pharmacyorg')),
                ('responder', models.ForeignKey(db_column='responder_id', on_delete=django.db.models.deletion.CASCADE, related_name='review_responses', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='pharmacypulse.review')),
            ],
            options={
                'db_table': 'review_responses',
            },
        ),
        migrations.CreateModel(
            name='ResponseCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(blank=True, db_column='pharmacy_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_counts', to='pharmacypulse.pharmacy')),
            ],
            options={
                'db_table': 'response_counts',
            },
        ),
        migrations.CreateModel(
            name='PinnedShortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortage', models.ForeignKey(blank=True, db_column='shortage_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by', to='pharmacypulse.drugshortage')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_shortages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pinned_shortages',
            },
        ),
        migrations.CreateModel(
            name='PharmacyTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('role', models.TextField(default='member')),
                ('invite_token', models.TextField(blank=True, null=True)),
                ('invited_by', models.IntegerField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='pharmacypulse.pharmacyorg')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_team_members',
            },
        ),
        migrations.CreateModel(
            name='PharmacyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(blank=True, db_column='pharmacy_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pharmacypulse.pharmacy')),
            ],
            options={
                'db_table': 'pharmacy_services',
            },
        ),
        migrations.CreateModel(
            name='PharmacyHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('day_name', models.TextField()),
                ('open_time', models.TextField(blank=True, null=True)),
                ('close_time', models.TextField(blank=True, null=True)),
                ('is_closed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(blank=True, db_column='pharmacy_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='pharmacypulse.pharmacy')),
            ],
            options={
                'db_table': 'pharmacy_hours',
            },
        ),
        migrations.CreateModel(
            name='PharmacyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.TextField(blank=True, null=True)),
                ('user_name', models.TextField(blank=True, null=True)),
                ('npi_number', models.TextField()),
                ('license_number', models.TextField()),
                ('supporting_docs', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='pending')),
                ('reviewed_at', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(blank=True, db_column='pharmacy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='pharmacypulse.pharmacy')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_claims',
            },
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='org',
            field=models.ForeignKey(blank=True, db_column='org_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to='pharmacypulse.pharmacyorg'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField(blank=True, default='')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '_benmore_notifications',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('zip_code', models.TextField(blank=True, null=True)),
                ('subscribed', models.IntegerField(default=1)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'newsletter_subscribers',
            },
        ),
        migrations.AddConstraint(
            model_name='drugshortage',
            constraint=models.UniqueConstraint(fields=('drug_name', 'manufacturer'), name='uniq_shortage_drug_manuf'),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='savedcomparison',
            constraint=models.UniqueConstraint(fields=('user', 'pharmacy'), name='uniq_saved_comparison_user_pharmacy'),
        ),
        migrations.AddConstraint(
            model_name='responsecount',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'month'), name='uniq_response_counts_pharmacy_month'),
        ),
        migrations.AddConstraint(
            model_name='pinnedshortage',
            constraint=models.UniqueConstraint(fields=('user', 'shortage'), name='uniq_pinned_user_shortage'),
        ),
        migrations.AddConstraint(
            model_name='pharmacyteammember',
            constraint=models.UniqueConstraint(fields=('org', 'email'), name='uniq_team_member_org_email'),
        ),
    ]
