# Generated by Django 4.2.30 on 2026-04-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(blank=True, default='')),
                ('stat', models.TextField(blank=True, default='')),
                ('head', models.TextField()),
                ('body', models.TextField()),
                ('cta', models.TextField(blank=True, default='')),
                ('src', models.TextField(blank=True, default='')),
                ('cta_link', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pharmacy_facts',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
