# Generated by Django 4.2.30 on 2026-05-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0003_user_plan_user_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='place_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='taxonomy_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='npi_number',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
