# Generated by Django 4.2.30 on 2026-05-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0004_pharmacy_place_id_pharmacy_taxonomy_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='authorized_official_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='authorized_official_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='enumeration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='secondary_taxonomies',
            field=models.TextField(blank=True, default=''),
        ),
    ]
