# Generated by Django 4.2.30 on 2026-05-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0005_pharmacy_authorized_official_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='enrichment_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
