# Generated by Django 4.2.30 on 2026-05-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0006_pharmacy_enrichment_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='chain_size',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
