# Generated by Django 4.2.30 on 2026-05-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0007_pharmacy_chain_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCentroid',
            fields=[
                ('zip', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(blank=True, default='', max_length=64)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('resolved_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'zip_centroids',
            },
        ),
    ]
