# Generated by Django 4.2.30 on 2026-08-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0010_seo_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyPublishable',
            fields=[
                ('pharmacy', models.OneToOneField(db_column='pharmacy_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='publishable', serialize=False, to='pharmacypulse.pharmacy')),
                ('publish_status', models.TextField(db_index=True, default='published')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField(default='Philadelphia')),
                ('state', models.TextField(default='PA')),
                ('zip', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('stock_confidence', models.IntegerField(default=0)),
                ('avg_wait_time', models.IntegerField(default=0)),
                ('avg_service_rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_digital', models.IntegerField(default=0)),
                ('website', models.TextField(blank=True, null=True)),
                ('npi_number', models.TextField(blank=True, db_index=True, null=True)),
                ('place_id', models.TextField(blank=True, db_index=True, null=True)),
                ('taxonomy_code', models.CharField(blank=True, default='', max_length=16)),
                ('enumeration_date', models.DateField(blank=True, null=True)),
                ('authorized_official_name', models.TextField(blank=True, default='')),
                ('authorized_official_title', models.TextField(blank=True, default='')),
                ('secondary_taxonomies', models.TextField(blank=True, default='')),
                ('chain_size', models.IntegerField(db_index=True, default=1)),
                ('claimed_by', models.IntegerField(blank=True, null=True)),
                ('org_id', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(default='active')),
                ('phone_wait_time', models.IntegerField(blank=True, null=True)),
                ('delivery_wait_time', models.IntegerField(blank=True, null=True)),
                ('delivery_rating', models.FloatField(default=0)),
                ('customer_service_hours', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pharmacies_publishable',
                'ordering': ['-total_reviews'],
            },
        ),
    ]
