# Generated by Django 4.2.30 on 2026-08-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0011_pharmacypublishable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacypublishable',
            name='admin_edited',
            field=models.BooleanField(default=False),
        ),
    ]
