# Generated by Django 4.2

from django.db import migrations, models


def dedupe_active_reviews(apps, schema_editor):
    """Keep a single active review per (pharmacy, user).

    The unique constraint created in the next migration can't be created while
    existing data still has duplicates (e.g. rows created before the
    one-review-per-pharmacy rule existed). Retain the best row per group —
    approved first, then most recent, then highest id — and delete the rest.

    This dedupe lives in its OWN migration (separate transaction) from the
    AddConstraint in 0015: the DELETE leaves pending deferred trigger events,
    and PostgreSQL refuses `CREATE INDEX` on a table with pending trigger
    events in the same transaction. Committing here clears them.
    """
    Review = apps.get_model("pharmacypulse", "Review")
    dup_groups = list(
        Review.objects
        .filter(pharmacy_id__isnull=False, user_id__isnull=False, deleted_at__isnull=True)
        .values("pharmacy_id", "user_id")
        .annotate(n=models.Count("id"))
        .filter(n__gt=1)
    )
    for grp in dup_groups:
        ids = list(
            Review.objects
            .filter(
                pharmacy_id=grp["pharmacy_id"],
                user_id=grp["user_id"],
                deleted_at__isnull=True,
            )
            .order_by(
                models.Case(
                    models.When(moderation_status="approved", then=models.Value(0)),
                    default=models.Value(1),
                ),
                "-created_at",
                "-id",
            )
            .values_list("id", flat=True)
        )
        Review.objects.filter(id__in=ids[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0013_user_facebook_id'),
    ]

    operations = [
        migrations.RunPython(dedupe_active_reviews, migrations.RunPython.noop),
    ]