# Generated by Django 4.2

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0014_review_unique_per_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at__isnull=True),
                fields=('pharmacy', 'user'),
                name='uniq_review_pharmacy_user',
            ),
        ),
    ]