# Generated by Django 4.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0015_review_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyCoveragePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.TextField()),
                ('plan_type', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(blank=True, db_column='pharmacy_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_plans', to='pharmacypulse.pharmacy')),
            ],
            options={
                'db_table': 'pharmacy_coverage_plans',
            },
        ),
        migrations.CreateModel(
            name='PharmacyInsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(blank=True, db_column='pharmacy_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_providers', to='pharmacypulse.pharmacy')),
            ],
            options={
                'db_table': 'pharmacy_insurance_providers',
            },
        ),
    ]