# Generated by Django 4.2.30 on 2026-08-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0016_pharmacyinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='listing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacypublishable',
            name='listing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
