# Generated by Django 4.2.30 on 2026-08-25 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0018_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_ip', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.TextField(default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(db_column='pharmacy_id', on_delete=django.db.models.deletion.CASCADE, related_name='closed_flags', to='pharmacypulse.pharmacy')),
                ('reporter_user', models.ForeignKey(blank=True, db_column='reporter_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_closed_flags', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_closed_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'closed_flags',
            },
        ),
    ]
