# Generated by Django 4.2.30 on 2026-09-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacypulse', '0019_closedflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='visit_purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='visit_timeframe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
